### ISSUE TITLE
problems with creat anim GIF under Windows

### ISSUE THREAD

**Issue by kmatze** [lecram/gifenc#1]
Hi Marcel-Lecram,

thx for your fast response. 
My system: Windows Vista, gcc 3.4.5 or tcc 0.9.26, Tcl/tk 8.0 and greater.

I compile with:

a) gcc -o example1.exe example1.c gifenc.c -std=c99
 gcc -o example2.exe example2.c gifenc.c -std=c99 

b) tcc -o example1.exe example1.c gifenc.c -std=c99
 tcc -o example2.exe example2.c gifenc.c -std=c99 

Here is the source of my attempt to use your formidable gifenc:

1) your example

#include "gifenc.h"

int
main()
{
 int i, j;
 int w = 120, h = 90;

 /* create a GIF */
 GIF *gif = new_gif(
 "example1.gif", /* file name */
 w, h, /* canvas size */
 (uint8_t []) { /* palette */
 0x00, 0x00, 0x00, /* 0 -> black */
 0xFF, 0x00, 0x00, /* 1 -> red */
 0x00, 0xFF, 0x00, /* 2 -> green */
 0x00, 0x00, 0xFF, /* 3 -> blue */
 },
 2, /* palette depth == log2(# of colors) */
 0 /* infinite loop */
 );
 /* draw some frames */
 for (i = 0; i < 4*6/3; i++) {
 for (j = 0; j < w*h; j++)
 gif->frame[j] = (i*3 + j) / 6 % 4;
 add_frame(gif, 10);
 }
 /* remember to close the GIF */
 close_gif(gif);
 return 0;
}

2) my attempt

#include "gifenc.h"

int
main()
{
 int i, j;
 int w = 120, h = 90;

 /* create a GIF */
 GIF *gif = new_gif(
 "example1.gif", /* file name */
 w, h, /* canvas size */
 (uint8_t []) { /* palette */
 0x00, 0x00, 0x00, /* 0 -> black */
 0xFF, 0x00, 0x00, /* 1 -> red */
 0x00, 0xFF, 0x00, /* 2 -> green */
 0x00, 0x00, 0xFF, /* 3 -> blue */
 },
 2, /* palette depth == log2(# of colors) */
 0 /* infinite loop */
 );
 /* draw some frames */
 for (i = 0; i < 4*6/3; i++) {
 for (j = 0; j < w*h; j++)
 gif->frame[j] = (i*3 + j) / 6 % 4;
 add_frame(gif, 10);
 }
 /* remember to close the GIF */
 close_gif(gif);
 return 0;
}

both compiles (a and b) with the same effect:
 the dimensions properties in explorer are right in both.
 I load both in PSP5 there is only one frame by both.
 I load in virtualdup with error messege "no video frames detected in GIF file.

What i do wrong?

![example1](https://cloud.githubusercontent.com/assets/27211712/24861636/c54c8734-1df9-11e7-9cd0-4f281847b5b7.gif)

![example2](https://cloud.githubusercontent.com/assets/27211712/24861637/c554bc6a-1df9-11e7-8e97-532395a8ea83.gif)
[example_source.zip](https://github.com/lecram/gifenc/files/910013/example_source.zip)

**Comment by lecram** [comment]
Windows is replacing "\n" with "\r\n".  
Can you test if it works after the last commit?

**Comment by kmatze** [comment]
Hi Lecram,
on pure c it works fine now! I will try it with tcl/tk. Thx very much.
Greetings - kmatze
