### ISSUE TITLE
Name prefixes

### ISSUE THREAD

**Issue by rxi** [lecram/gifenc#3]
C libraries frequently prefix their function and type names (eg: `SDL_`, `lua_`, `stbi_`) as to reduce the chance of name conflicts with existing functions and types. Currently gifenc does not do this, which in the case of `add_frame` especially, seems like it may cause an issue.

Would you be open to adding a prefix to the function names, resulting in something like: `gifenc_add_frame`, `gifenc_new_gif`, `gifenc_close_gif` and `gifenc_GIF`? Something like `ge_` may be more favourable due to its shorter length.

Otherwise the library seems great, thanks for the excellent work!

**Comment by lecram** [comment]
Thanks for pointing this out. I went with `ge_`.

Your kind words are appreciated.
