### ISSUE TITLE
You are the best.

### ISSUE THREAD

**Issue by cnlohr** [lecram/gifenc#4]
Dude.  This is the bees' knees.  I googled "make animated gif C" and got this and was NOT DISAPPOINTED! Took me 5 minutes to implement and was flawless.

**Comment by lecram** [comment]
Thanks for the feedback! I'm glad it worked for you.

**Comment by cnlohr** [comment]
I wish doing submodules with git wasn't so janky.  I used this with rawdraw in a specific project and I think I may C&P (with credit) this over there for use in other projects.

**Comment by lecram** [comment]
Only problem with copy & paste is keeping your version up-to-date. It's just a small library and will always be, but I'm planning a few minor changes in the near future -- fixing some bugs and improving compression. But feel free to copy & paste it anywhere. Attribution is not required. If it's useful, just steal it.
